CREATE TABLE user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL
);

CREATE TABLE clipboard (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  content VARCHAR(200) NOT NULL,
  created_at DATETIME NOT NULL
);
